### PR TITLE
Run project and example tests in Travis CI

### PR DESCRIPTION
**Pull request by davehunt**
Summary
==============================

This patch adds the necessary configuration for running the project and example tests in Travis CI. To get this running, somebody with access will need to enable the project in their Travis CI account for this repository.

Additional Details
==============================

I hit an issue with the maven-gpg-plugin dependency, which I have temporarily removed to demonstrate the tests running. I'm not sure how to resolve this issue, but thought it might be at least valuable to provide the Travis CI configuration and see if you had some thoughts on this blocker.

You can see a successful build running on my branch at https://travis-ci.org/davehunt/jenkins-spock/builds/437189104

Checklist
==============================

Testing
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

* [X] I have manually verified that my code changes do the right thing.
* [X] I have run the tests and verified that my changes do not introduce any regressions.
* [ ] ~~I have written unit tests to verify that my code changes do the right thing and to protect my code against regressions~~

Documentation
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

* [ ] ~~I have updated the "Unreleased" section of `CHANGELOG.md` with a brief description of my changes.~~
* [ ] ~~I have updated code comments - both GroovyDoc/JavaDoc-style comments and inline comments - where appropriate.~~
* [X] I have read `CONTRIBUTING.md` and have followed its guidance.

### CODE REVIEW

**Comment by awittha** [comment]
Thank you! This will be helpful. We're working on getting a TravisCI setup connected.

Could you elaborate on the issue with `mvn-gpg-plugin`? Sonatype/maven-central requires a PGP signature on uploaded artifacts - so we don't really want to discard the plugin.

**Comment by davehunt** [comment]
I've pushed to my travis-gpg branch the changes without disabling the plugin. You can see the error this raises in Travis CI here: https://travis-ci.org/davehunt/jenkins-spock/builds/438593024. I believe the issue is related to these lines in the output:

> gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available

**Comment by awittha** [comment]
Ah, OK, simple enough: Travis just doesn't have a PGP identity configured - nothing huge to worry about.

Thank you!

**Comment by davehunt** [comment]
> Ah, OK, simple enough: Travis just doesn't have a PGP identity configured - nothing huge to worry about.

Is that something I can help with? Would you like me to update this pull request by removing the commit that removes the gpg plugin?

**Comment by awittha** [comment]
No, please leave it: we'll need Travis to be able to GPG-sign artifacts. We'll be able to use this PR as a failing test-case to drive us towards a successful GPG-enabled TravisCI 👍

**Comment by davehunt** [comment]
Perhaps I wasn't clear. This pull request includes the **removal** of the gpg plugin, so that I could demonstrate the tests passing in Travis CI. I created a separate branch (but not pull request) to demonstrate the build failing in Travis CI with the plugin still present. It sounds like you want the pull request to keep the gpg plugin and fail, such that it will only pass once you have gpg enabled in Travis. If this is correct then I will restore the gpg plugin and update this pull request.

**Comment by awittha** [comment]
Ah, ok. I just clicked into https://travis-ci.org/davehunt/jenkins-spock/builds/438593024 and didn't look too closely at its provenance.

*A TravisCi-ready branch/PR that _fails_ because GPG isn't set up for HomeAway on that Travis account,* would be most useful. Once we get Travis set up, that PR will start passing and then we can merge with confidence.

**Comment by davehunt** [comment]
Okay, great. I've updated this pull request, so when you have Travis CI enabled for this repository, this pull request should start to fail due to the GPG issue. Once that's resolved this should then pass, and could be merged.

**Comment by awittha** [comment]
We waited long enough that GitHub Actions matured to where we could use those. `jenkins-spock`'s CI/CD needs are now handled by GitHub Actions.

**Pull request closed without merging**
